import Foundation
@testable import Macterm
import Testing

@MainActor
struct WorkspaceSerializerTests {
    // Round-trip: snapshot -> restore -> compare topology.
    private func roundTrip(_ workspaces: [UUID: Workspace]) -> [Workspace] {
        let snaps = WorkspaceSerializer.snapshot(workspaces).workspaces
        let valid = Set(workspaces.keys)
        return WorkspaceSerializer.restore(from: snaps, validIDs: valid)
    }

    @Test
    func round_trip_single_tab_single_pane_preserves_paths() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp/a")
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped.count == 1)
        #expect(roundTripped[0].tabs.count == 1)
        if case let .pane(p) = roundTripped[0].tabs[0].splitRoot {
            #expect(p.projectPath == "/tmp/a")
        } else {
            Issue.record("expected leaf")
        }
    }

    @Test
    func round_trip_preserves_tab_and_workspace_ids() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let tabID = ws.tabs[0].id
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped[0].projectID == ws.projectID)
        #expect(roundTripped[0].tabs[0].id == tabID)
    }

    @Test
    func round_trip_preserves_nested_topology() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let (tree, ids) = build(H(pane("a"), V(pane("b"), pane("c"), ratio: 0.3), ratio: 0.4))
        ws.tabs[0].splitRoot = tree

        let roundTripped = roundTrip([ws.projectID: ws])
        let restoredRoot = roundTripped[0].tabs[0].splitRoot

        // Pane IDs are regenerated by restoreNode — check structure via
        // rendering with a new name map keyed on path, which we can
        // reconstruct because each pane's projectPath is unique to /.
        #expect(restoredRoot.allPanes().count == 3)
        // Topology: outer horizontal (0.4), inner vertical (0.3).
        guard case let .split(outer) = restoredRoot, outer.direction == .horizontal else {
            Issue.record("expected outer horizontal split")
            return
        }
        #expect(abs(outer.ratio - 0.4) < 0.0001)
        guard case let .split(inner) = outer.second, inner.direction == .vertical else {
            Issue.record("expected inner vertical split")
            return
        }
        #expect(abs(inner.ratio - 0.3) < 0.0001)
        _ = ids
    }

    @Test
    func round_trip_preserves_custom_title() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        ws.tabs[0].customTitle = "My Custom Title"
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped[0].tabs[0].customTitle == "My Custom Title")
    }

    @Test
    func round_trip_preserves_active_tab_when_valid() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let second = ws.createTab(projectPath: "/tmp")
        ws.selectTab(second.id)
        let roundTripped = roundTrip([ws.projectID: ws])
        #expect(roundTripped[0].activeTabID == second.id)
    }

    @Test
    func round_trip_falls_back_to_first_tab_when_active_missing() {
        // Simulate a corrupt snapshot where activeTabID doesn't match any tab.
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let snaps = WorkspaceSerializer.snapshot([ws.projectID: ws]).workspaces
        var snap = snaps[0]
        snap = WorkspaceSnapshot(projectID: snap.projectID, activeTabID: UUID(), tabs: snap.tabs)
        let restored = WorkspaceSerializer.restore(from: [snap], validIDs: [ws.projectID])
        #expect(restored.count == 1)
        // Workspace.init treats an unknown activeTabID as if nil and picks the first tab.
        #expect(restored[0].activeTabID == restored[0].tabs.first?.id)
    }

    @Test
    func restore_skips_workspaces_for_removed_projects() {
        let kept = Workspace(projectID: UUID(), projectPath: "/tmp/a")
        let dropped = Workspace(projectID: UUID(), projectPath: "/tmp/b")
        let snaps = WorkspaceSerializer.snapshot([kept.projectID: kept, dropped.projectID: dropped]).workspaces
        let restored = WorkspaceSerializer.restore(from: snaps, validIDs: [kept.projectID])
        #expect(restored.count == 1)
        #expect(restored[0].projectID == kept.projectID)
    }

    @Test
    func restore_skips_workspaces_with_no_tabs() {
        // Build a hand-rolled empty-tabs snapshot.
        let pid = UUID()
        let snap = WorkspaceSnapshot(projectID: pid, activeTabID: nil, tabs: [])
        let restored = WorkspaceSerializer.restore(from: [snap], validIDs: [pid])
        #expect(restored.isEmpty)
    }

    @Test
    func snapshot_preserves_focused_pane_id() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let tab = ws.tabs[0]
        let (tree, ids) = build(H(pane("a"), pane("b")))
        tab.splitRoot = tree
        tab.focusedPaneID = ids["b"]
        let snaps = WorkspaceSerializer.snapshot([ws.projectID: ws]).workspaces
        #expect(snaps[0].tabs[0].focusedPaneID == ids["b"])
    }

    @Test
    func round_trip_preserves_done_attention_state() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        if case let .pane(p) = ws.tabs[0].splitRoot {
            p.recordUserInteraction()
            p.markCommandRunning()
            p.markCommandFinished()
            #expect(p.executionState == .done)
        }
        let roundTripped = roundTrip([ws.projectID: ws])
        if case let .pane(p) = roundTripped[0].tabs[0].splitRoot {
            #expect(p.executionState == .done)
        } else {
            Issue.record("expected leaf")
        }
    }

    @Test
    func round_trip_does_not_persist_idle_or_running() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        if case let .pane(p) = ws.tabs[0].splitRoot {
            // Idle stays idle.
            #expect(p.executionState == .idle)
        }
        let idleRound = roundTrip([ws.projectID: ws])
        if case let .pane(p) = idleRound[0].tabs[0].splitRoot {
            #expect(p.executionState == .idle)
        }
    }

    @Test
    func restore_done_is_cleared_by_acknowledge() {
        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        if case let .pane(p) = ws.tabs[0].splitRoot {
            p.recordUserInteraction()
            p.markCommandRunning()
            p.markCommandFinished()
        }
        let roundTripped = roundTrip([ws.projectID: ws])
        if case let .pane(p) = roundTripped[0].tabs[0].splitRoot {
            #expect(p.executionState == .done)
            p.acknowledgeCommandCompletion()
            #expect(p.executionState == .idle)
        } else {
            Issue.record("expected leaf")
        }
    }

    @Test
    func roundtrip_via_WorkspaceStore_on_disk() {
        // End-to-end: encode, write to a temp file, load back, restore.
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = WorkspaceStore(fileURL: tmp)

        let ws = Workspace(projectID: UUID(), projectPath: "/tmp")
        let (tree, _) = build(H(pane("a"), pane("b")))
        ws.tabs[0].splitRoot = tree

        let snap = WorkspaceSerializer.snapshot([ws.projectID: ws])
        store.save(workspaces: snap.workspaces, groups: snap.groups)
        let reloaded = store.load()
        #expect(reloaded.workspaces.count == 1)
        #expect(reloaded.workspaces[0].projectID == ws.projectID)

        let restored = WorkspaceSerializer.restore(from: reloaded.workspaces, validIDs: [ws.projectID])
        #expect(restored[0].tabs[0].splitRoot.allPanes().count == 2)
    }

    // MARK: - Linked groups

    @Test
    func round_trip_restores_linked_group_across_projects() throws {
        // Two single-pane projects; splice p2's tab into p1's tab to mimic a
        // cross-project link, then round-trip through disk.
        let p1 = UUID()
        let p2 = UUID()
        let ws1 = Workspace(projectID: p1, projectPath: "/tmp1")
        let ws2 = Workspace(projectID: p2, projectPath: "/tmp2")
        let host = ws1.tabs[0]
        let member = ws2.tabs[0]
        let hostPaneID = try #require(host.focusedPaneID)

        let subtree = member.splitRoot
        subtree.assignOriginTab(member.id)
        let (root, seam) = host.splitRoot.splicing(subtree: subtree, atPaneID: hostPaneID, edge: .right)
        #expect(seam != nil)
        host.splitRoot = root

        let group = TabGroup(hostTabID: host.id, colorIndex: 2)
        group.memberOrder = [host.id, member.id]
        host.linkedGroupID = group.id
        member.linkedGroupID = group.id

        let workspaces = [p1: ws1, p2: ws2]
        let snap = WorkspaceSerializer.snapshot(workspaces, groups: [group.id: group])

        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-group-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = WorkspaceStore(fileURL: tmp)
        store.save(workspaces: snap.workspaces, groups: snap.groups)

        let loaded = store.load()
        let restoredWorkspaces = WorkspaceSerializer.restore(from: loaded.workspaces, validIDs: [p1, p2])
        var byProject: [UUID: Workspace] = [:]
        for ws in restoredWorkspaces {
            byProject[ws.projectID] = ws
        }
        let (groups, nextColor) = WorkspaceSerializer.restoreGroups(loaded.groups, into: byProject)

        #expect(groups.count == 1)
        #expect(nextColor == 3)
        let restoredGroup = try #require(groups[group.id])
        #expect(restoredGroup.memberOrder == [host.id, member.id])

        let restoredHost = try #require(byProject[p1]?.tabs.first { $0.id == host.id })
        #expect(restoredHost.splitRoot.allPanes().count == 2)
        // Pane ids are regenerated on restore, but origin tags survive — find the
        // member's pane by origin and check it kept its own project identity.
        let memberPane = restoredHost.splitRoot.allPanes().first { $0.originTabID == member.id }
        #expect(memberPane != nil)
        #expect(memberPane?.projectID == p2)

        let restoredMember = try #require(byProject[p2]?.tabs.first { $0.id == member.id })
        #expect(restoredMember.linkedGroupID == group.id)
        #expect(restoredMember.splitRoot.allPanes().count == 1)
        #expect(restoredMember.splitRoot.allPanes().first?.originTabID == member.id)
    }

    @Test
    func load_v3_file_clears_persisted_attention_bits() throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-v3-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        let store = WorkspaceStore(fileURL: tmp)
        let projectID = UUID()
        let tabID = UUID()
        let paneID = UUID()
        let file = WorkspacesFile(
            version: 3,
            workspaces: [WorkspaceSnapshot(
                projectID: projectID,
                activeTabID: tabID,
                tabs: [TabSnapshot(
                    id: tabID,
                    customTitle: nil,
                    focusedPaneID: paneID,
                    splitRoot: .pane(PaneSnapshot(
                        id: paneID,
                        projectPath: "/tmp",
                        needsAttention: true
                    ))
                )]
            )]
        )
        let encoder = JSONEncoder()
        try encoder.encode(file).write(to: tmp)

        let restored = WorkspaceSerializer.restore(from: store.load(), validIDs: [projectID])

        #expect(restored.first?.tabs.first?.executionState == .idle)
    }

    @Test
    func load_from_missing_file_returns_empty() {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-doesnotexist-\(UUID().uuidString).json")
        let store = WorkspaceStore(fileURL: tmp)
        #expect(store.load().workspaces.isEmpty)
    }

    @Test
    func load_from_malformed_file_returns_empty() throws {
        let tmp = FileManager.default.temporaryDirectory
            .appendingPathComponent("macterm-tests-malformed-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: tmp) }
        try Data("not valid json {".utf8).write(to: tmp)
        let store = WorkspaceStore(fileURL: tmp)
        #expect(store.load().workspaces.isEmpty)
    }
}
